import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Main from "../components/Main";
import About from "../components/About";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Gabe Morring</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/gm-logo.png" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
    </div>
  );
}
